language: node_js
node_js:
  - "0.12.7"
services:
  - rethinkdb
install:
  - mkdir $HOME/go
  - export GOPATH=$HOME/go
before_script:
  - cd client && npm install &&  npm install -g gulp
  - node -v
script:
  - npm test
